### ISSUE TITLE
Deploy with a Helm chart

### ISSUE THREAD

**Issue by LeoColomb** [netbox-community/netbox-operator#105]
### What would you like to be added?

It would be very handful to be able to deploy the operator with a Helm chart.
This would help to keep track of:
* Different versions
* Relative container images
* CRD
* The overall package

### Why is this needed?

Two possibilities:
* Generating/maintaining a Helm chart in this same repo.
  * There is no good-automated way per se, but:
    * Creating a new chart is fairly easy
    * Automation might come relatively soon https://github.com/kubernetes-sigs/kubebuilder/pull/3632
  * Might be a bit redundant with the manifest, but:
    * Can be handled with some packing scripts
* Adding a separate Helm chart to [NetBox charts repository](https://github.com/netbox-community/netbox-chart)
  * Part of the effort to provide good quality charts
  * Less development ready but more production ready
  * But also makes repo structure a bit less obvious

**Comment by jstudler** [comment]
Hi @LeoColomb,

Thanks for creating this issue. I fully agree that a helm chart would be beneficial. From my point of view, it makes most sense to add it to the NetBox charts repository so the charts related to NetBox are collected in and distributed from a single place. This is also similar to how projects like Argo, Flux or Testkube handle Helm charts. If/when Kubebuilder adds the capability to auto generate charts for Kubernetes Operators, we can for sure reconsider moving the chart to the netbox-operator repo. What do you think?

**Comment by LeoColomb** [comment]
Sounds perfect 👌
As a first step, I just initiated the chart based on the current config folder.
https://github.com/netbox-community/netbox-chart/pull/397

Very much still a work in progress, but seems fairly simple to sort out.
